version: '3.8'

services:
  deepstream:
    image: hieung/deepstream-face-recognition:custom
    runtime: nvidia
    privileged: true
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    ports:
      - "5400:5400/udp"
      - "8554:8554"
      - "1935:1935"
    working_dir: /app
    stdin_open: true
    tty: true
    command: bash

